### ISSUE TITLE
Type Error: Failed to convert string to float 'N/'

### ISSUE THREAD

**Issue by JagjitBhatia** [CrypticSignal/better-ffmpeg-progress#12]
Get an error: [Error] could not convert string to float: 'N/' every time I try to run it. Might be due to a different FFMPEG version. 

PR for fix: #11

**Comment by CrypticSignal** [comment]
Please upgrade to `v2.1.1` with `pip3 install better-ffmpeg-progress --upgrade` and let me know if you ever run into this issue. For now, I will close this issue.
