### ISSUE TITLE
Command after its done will exit out the rest of the code

### ISSUE THREAD

**Issue by savke24** [CrypticSignal/better-ffmpeg-progress#15]
Hi, 

I am using this script in more complex code and it looks like that after ffmpeg proccess is done , this command would stop further execution of the code...
It looks like " sys.exit() at the line 160  " is responsible for that kind of behaviour.

**Comment by CrypticSignal** [comment]
Hi @savke24, thank you for opening this issue. You are correct, `sys.exit()` is responsible for this. I will update this package and let you know when the updated version is released.

**Comment by CrypticSignal** [comment]
@savke24 Please upgrade Better FFmpeg Process to v2.1.2 with `pip install better-ffmpeg-progress --upgrade` and you will no longer run into the issue you mentioned.
