### ISSUE TITLE
[FR] Use `rich` instead of `tqdm`

### ISSUE THREAD

**Issue by F-park** [CrypticSignal/better-ffmpeg-progress#19]
### Future Request Reason
[rich](https://github.com/Textualize/rich#rich-print) can make console colorful, both text and progress, I think it adapts this project.

### Solution
If you agree this change, I will work in #17

**Comment by CrypticSignal** [comment]
You can replace `tqdm` with `rich`, as long as (at minimum) we still have a progress bar, percentage progress and estimate time of completion.

**Comment by F-park** [comment]
> @F-park You don't need to add this in #17, I can work on this myself one day.

OK

**Comment by CrypticSignal** [comment]
@F-park tqdm has been replaced with Rich in v2.1.8.
