### ISSUE TITLE
[Better FFmpeg Process] invalid literal for int() with base 10: 'N/A'

### ISSUE THREAD

**Issue by WALLY-TAMER** [CrypticSignal/better-ffmpeg-progress#23]
Version : 2.1.4

I get this error nearly on every single conversion and i think i know where is the problem ( my knowledge isn't that good )
the `value` variable is what causing this in line 81
`seconds_processed = round(int(value) / 1_000_000, 1)`
I printed The Value just before this line and that was the output :

> Running: ffmpeg -i D:\Python_FFMPEG\Input\Sickflick - Copy (2).mp4 D:\Python_FFMPEG\Output\Sickflick - Copy (2).mp4 -hide_banner -loglevel verbose -progress pipe:1 -nostats
> 
>   1%|██                                                                                                                                                                     | 0/10.3 [00:00<?, ?s/s]
> 
> Value : 3200000
>  31%|█████████████████████████████████████████████████████▍                               | 3.2/10.3 [00:05<00:12,  1.74s/s]
>  Value : N/A
> [Better FFmpeg Process] invalid literal for int() with base 10: 'N/A'

**Comment by CrypticSignal** [comment]
@WALLY-TAMER Thank you for reporting this. I will fix this issue and get back to you.

**Comment by CrypticSignal** [comment]
@WALLY-TAMER This issue should no longer occur in `v2.1.5`. Could you upgrade with `pip3 install better-ffmpeg-progress --upgrade` and confirm this?

**Comment by WALLY-TAMER** [comment]
@CrypticSignal I've been testing it for the last 2 days and it seems to be working fine, Thanks for your effort ♥
