### ISSUE TITLE
no progress view

### ISSUE THREAD

**Issue by 276397082** [CrypticSignal/better-ffmpeg-progress#24]
```
from better_ffmpeg_progress import FfmpegProcess
def FfmpegProcess_on():
    # Pass a list of FFmpeg arguments, like you would if using subprocess.run()
    process = FfmpegProcess(
        [
            ".\\ffmpeg\\ffmpeg",
            "-y",
            "-i",
            "X:/UpupooResource/2000141996/科技感设计.mp4",
            "-r",
            "10",
            "-pix_fmt",
            "yuv420p",
            "-vcodec",
            "libx264",
            "-preset",
            "veryfast",
            "-profile:v",
            "baseline",
            "-crf",
            "23",
            "-acodec",
            "aac",
            "-b:a",
            "32k",
            "-strict",
            "-5",
            "c:\\1.mp4",
        ]
    )

    # Use the run method to run the FFmpeg command.
    process.run()


if __name__ == "__main__":
    FfmpegProcess_on()
```

> result：
Running: .\ffmpeg\ffmpeg -y -i X:/UpupooResource/2000141996/科技感设计.mp4 -r 10 -pix_fmt yuv420p -vcodec libx264 -preset veryfast -profile:v baseline -crf 23 -acodec aac -b:a 32k -strict -5 c:\1.mp4 -hide_banner -loglevel verbose

PS C:\Users\Administrator\Desktop>

**Comment by CrypticSignal** [comment]
Does running ` .\ffmpeg\ffmpeg -y -i X:/UpupooResource/2000141996/科技感设计.mp4 -r 10 -pix_fmt yuv420p -vcodec libx264 -preset veryfast -profile:v baseline -crf 23 -acodec aac -b:a 32k -strict -5 c:\1.mp4 -hide_banner -loglevel verbose` directly in your terminal work and converts the file?

**Comment by CrypticSignal** [comment]
Closing this as there has been no response. @276397082 please upgrade this package with `pip install better-ffmpeg-progress --upgrade` and if you still encounter this issue, let me know if directly entering the same command in the terminal works and what your operating system is.
