### ISSUE TITLE
Exists file alert

### ISSUE THREAD

**Issue by mammothrider** [CrypticSignal/better-ffmpeg-progress#25]
The ffmpeg alert "File 'xxx' already exists. Overwrite? [y/N]" is hidden by the progress bar, but can still press y and pass it.

Maybe show this alert before the bar, or add a param like "exist_ok"?

**Comment by mammothrider** [comment]
Also, the subprocess seems not working well with cmd array which has non-ascii input, so I just change my code to
`
        with open(ffmpeg_output_file, "a") as f:
            cmd = " ".join(self._ffmpeg_args)
            process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=f)
            print(f"\nRunning: {cmd}\n")
`

**Comment by CrypticSignal** [comment]
@mammothrider I don't understand what the issue is. `<filename> already exists. Overwrite? [Y/N]` is not hidden by the progress bar and it is shown before the progress bar.,

Example terminal output if you enter `y`:
```
PS C:\Users\hshaf\Desktop\bfp-test> python main.py
The duration of 1.webm has been detected as 168.168 seconds.
output.mp3 already exists. Overwrite? [Y/N]: y

Running: ffmpeg -y -i 1.webm -c:a libmp3lame output.mp3 -hide_banner -loglevel verbose -progress pipe:1 -nostats

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 156.8/168.2 [00:01<00:00, 149.32s/s]

Done! To see FFmpeg's output, check out ffmpeg_output\[1.webm].txt
```
Example terminal output if you enter `n`:
```
PS C:\Users\hshaf\Desktop\bfp-test> python main.py
The duration of 1.webm has been detected as 168.168 seconds.
output.mp3 already exists. Overwrite? [Y/N]: n
FFmpeg will not run as the output filename already exists, and you do not want it to be overwritten.
```

**Comment by mammothrider** [comment]
was running on v2.1.5 and got this problem.
just upgrade and try the v2.3.1, problem fixed.
