### ISSUE TITLE
Syntax error in `better_ffmpeg_progress.py`

### ISSUE THREAD

**Issue by phlummox** [CrypticSignal/better-ffmpeg-progress#26]
This line:

https://github.com/CrypticSignal/better-ffmpeg-progress/blob/2564147cfa7e66a8d5ccbfc7e1dc313fb7d6b6df/better_ffmpeg_progress/better_ffmpeg_progress.py#L282

which was introduced by commit 291e58e (version 2.4.1), is reported as a syntax error by my version of python (3.10.12), and certainly doesn't look at all correct. It seems to be in at least all the versions from 2.4.1 to 2.5.6 (current).

If the repository were set up to run Pylint (or most other static checking tools) when a commit is pushed, it would be possible to detect this sort of issue automatically; see [here](https://github.com/actions/starter-workflows/blob/main/ci/pylint.yml) for an example of how to do it. When I run pylint over the code, it gets flagged with the following output:

```
************* Module better_ffmpeg_progress.better_ffmpeg_progress
better_ffmpeg_progress.py:282:22: E0001: Parsing failed: 'unexpected character after line continuation character (better_ffmpeg_progress.better_ffmpeg_progress, line 282)' (syntax-error)
************* Module better_ffmpeg_progress
__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module better_ffmpeg_progress.__init__
__init__.py:1:0: E0001: Cannot import 'better_ffmpeg_progress' due to 'unexpected character after line continuation character (better_ffmpeg_progress.better_ffmpeg_progress, line 282)' (syntax-error)

--------------------------------------
Your code has been rated at -100.00/10
```

It might be an idea to do some sort of end-to-end testing, as well.

**Comment by phlummox** [comment]
I just noticed your changelog is in the README.md - I didn't notice, and originally assumed you didn't have one. I hope you won't mind my saying so, but it might be a bit more obvious if it were in a separate CHANGELOG.md file - people coming to report a bug may not see the end of the README.

**Comment by CrypticSignal** [comment]
I don't get such an error when runing pylint. Anyway, I suspect it's because of having double quotes within double quotes, in which case changing the line to:
```py
 f"{'\n' if self._duration_secs is None else ''}[KeyboardInterrupt] FFmpeg process(es) killed." 
```
should do the trick.

I'll make this change later today or tomorrow.

Moving the changelog to a `CHANGELOG.md` file is a good idea - I will make this change.

**Comment by CrypticSignal** [comment]
@phlummox Try upgrading to v2.5.7 with `pip install -r better-ffmpeg-progress --upgrade` and let me know if you're able to use Better FFmpeg Progress without any issues.
