### ISSUE TITLE
Few suggestions for cleaner output

### ISSUE THREAD

**Issue by jclerc** [CrypticSignal/better-ffmpeg-progress#27]
Hi!

I'm having a nice time using your tool, thanks for making it!

I have a few suggestions about the output, which can be improved and configured a little more.

Currently, with `print_detected_duration=False`, the output of processing a single file looks like this:
```
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------
Executing: ffmpeg -i IMG_0106.MOV -c:v libx265 -crf 28 -preset medium -c:a aac -b:a 128k -tag:v hvc1 IMG_0106.x265.MOV -hide_banner -loglevel verbose -progress pipe:1 -stats_period 0.1 -nostats
⠋ IMG_0106.MOV ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━  95% 0:00:01 --:--
FFmpeg process completed.
```

Which is quite verbose, especially when running this in a loop of dozens of files.

I would like to have the following:
```
✓ IMG_0106.MOV ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  100% 0:00:01 00:00
```

or could be as simple as:
```
✓ IMG_0106.MOV ━ 100% completed!
```

So:
- no lines at the start
- disable printing the command executed
- instead of printing `FFmpeg process completed`, overwrite the previous line to show a "completed" status

Of course it can be options, so it won't break current output.

If I've time soon I might do a PR, but if you have time I'll let you make the changes :D

**Comment by CrypticSignal** [comment]
- Removed the line at the start if `print_detected_duration` is `False`

- Made printing the FFmpeg command being executed optional. You must pass `print_command=True` to the `run` method if you would like the command to be printed.

- When a progress bar can be displayed, on successful process completion, the process bar is removed and replaced with something like `✓ Processed 100% of IMG_0106.MOV`

@jclerc Could you update to the latest version by running `pip install better-ffmpeg-progress --upgrade`, test the aforementioned changes and let me know if all is good?

**Comment by jclerc** [comment]
That was quick!

Just tested, it works nice :D Really appreciated, thanks!
